using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OneFrameEventsSourceGenerator
{
    public static class SimulationEventSourceGeneratorUtility
    {
        public static void Generate(StructDeclarationSyntax node, GeneratorExecutionContext context, FileLogger logger)
        {
            var component = node.Identifier.Text;
            var @namespace = CodeBuildHelper.GetNamespace(node);
            var assembly = context.Compilation.AssemblyName;
                    
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Processing component {@namespace}.{component} [{assembly}]");
            
            GenerateRequest(component, @namespace, out var requestFile, out var requestCode);
            context.AddSource(requestFile, requestCode);
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Generated source {requestFile}");
                    
            GenerateSystem(component, @namespace, out var systemFile, out var systemCode);
            context.AddSource(systemFile, systemCode);
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Generated source {systemFile}");
        }
        
        private static void GenerateRequest(string component, string @namespace, out string file, out string code)
        {
            var request = CodeBuildHelper.RequestName(component);
            
            file = $"{request}.cs";
            
            code = $@"// This code was generated by the OneFrameEventsSourceGenerator.

using Unity.Entities;

namespace {@namespace}
{{
    public struct {request} : IComponentData
    {{
        public {component} Value;
    }}
}}
";
        }

        private static void GenerateSystem(string component, string @namespace, out string file, out string code)
        {
            var system = CodeBuildHelper.SystemName(component);
            var request = CodeBuildHelper.RequestName(component);
            
            file = $"{system}.cs";
            
            code = $@"// This code was generated by the OneFrameEventsSourceGenerator.

using {CodeBuildHelper.Namespace};
using Unity.Burst;
using Unity.Collections;
using Unity.Entities;

namespace {@namespace}
{{
    [BurstCompile]
    [UpdateInGroup(typeof({CodeBuildHelper.SystemGroup}))]
    [WorldSystemFilter(WorldSystemFilterFlags.ClientSimulation | WorldSystemFilterFlags.ServerSimulation | WorldSystemFilterFlags.LocalSimulation)]
    public partial struct {system} : ISystem
    {{
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {{
            state.RequireForUpdate<EndSimulationEntityCommandBufferSystem.Singleton>();

            using var queries = new NativeList<EntityQuery>(Allocator.Temp);
            queries.Add(new EntityQueryBuilder(Allocator.Temp)
                .WithAll<{component}>()
                .Build(ref state));
            queries.Add(new EntityQueryBuilder(Allocator.Temp)
                .WithAll<{request}>()
                .Build(ref state));
            state.RequireAnyForUpdate(queries.AsArray());
        }}

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {{
            var ecb = SystemAPI
                .GetSingleton<EndSimulationEntityCommandBufferSystem.Singleton>()
                .CreateCommandBuffer(state.WorldUnmanaged);
            
            state.Dependency = new DestroyJob {{ Ecb = ecb.AsParallelWriter() }}.ScheduleParallel(state.Dependency);
            state.Dependency = new RequestJob {{ Ecb = ecb.AsParallelWriter() }}.ScheduleParallel(state.Dependency);
        }}

        [BurstCompile]
        [WithAll(typeof({component}))]
        public partial struct DestroyJob : IJobEntity
        {{
            public EntityCommandBuffer.ParallelWriter Ecb;
            void Execute(Entity entity, [ChunkIndexInQuery] int chunkIndex)
            {{
                Ecb.DestroyEntity(chunkIndex, entity);
            }}
        }}

        [BurstCompile]
        public partial struct RequestJob : IJobEntity
        {{
            public EntityCommandBuffer.ParallelWriter Ecb;
            void Execute(Entity entity, {request} request, [ChunkIndexInQuery] int chunkIndex)
            {{
                Ecb.AddComponent(chunkIndex, Ecb.CreateEntity(chunkIndex), request.Value);
                Ecb.DestroyEntity(chunkIndex, entity);
            }}
        }}
    }}
}}
";
        }
    }
}