using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OneFrameEventsSourceGenerator
{
    public static class SimulationEventSourceGeneratorUtility
    {
        public static void Generate(TypeDeclarationSyntax node, GeneratorExecutionContext context, FileLogger logger)
        {
            var component = node.Identifier.Text;
            var @namespace = CodeBuildHelper.GetNamespace(node);
            var assembly = context.Compilation.AssemblyName;
            var fullName = CodeBuildHelper.GetFullName(@namespace, component);
                    
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Processing component {fullName} [{assembly}]");
            
            GenerateRequest(component, @namespace, out var requestFile, out var requestCode);
            context.AddSource(requestFile, requestCode);
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Generated source {requestFile}");
                    
            GenerateSystem(component, @namespace, out var systemFile, out var systemCode);
            context.AddSource(systemFile, systemCode);
            logger.Info($"{nameof(SimulationEventSourceGeneratorUtility)}: Generated source {systemFile}");
        }
        
        private static void GenerateRequest(string component, string @namespace, out string file, out string code)
        {
            var request = CodeBuildHelper.RequestName(component);
            
            file = $"{request}.cs";
            
            code = $@"// This code was generated by the OneFrameEventsSourceGenerator.

using Unity.Entities;

{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"namespace {@namespace}
{{")}
    public struct {request} : IComponentData
    {{
        public {component} Value;
    }}
{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"
}}")}
";
        }

        private static void GenerateSystem(string component, string @namespace, out string file, out string code)
        {
            var system = CodeBuildHelper.SystemName(component);
            var request = CodeBuildHelper.RequestName(component);
            
            file = $"{system}.cs";
            
            code = $@"// This code was generated by the OneFrameEventsSourceGenerator.

using {CodeBuildHelper.Namespace};
using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Collections;
using Unity.Entities;

{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"namespace {@namespace}
{{")}
    [BurstCompile]
    [UpdateInGroup(typeof({CodeBuildHelper.SystemGroup}))]
    [WorldSystemFilter(WorldSystemFilterFlags.ClientSimulation | WorldSystemFilterFlags.ServerSimulation | WorldSystemFilterFlags.LocalSimulation)]
    public partial struct {system} : ISystem
    {{
        private EntityQuery _ecbSingletonQuery;
        private EntityQuery _eventQuery;
        private EntityQuery _requestQuery;

        private EntityTypeHandle _entityType;
        private ComponentTypeHandle<{request}> _requestType;
        
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {{
            _ecbSingletonQuery = new EntityQueryBuilder(Allocator.Temp)
                .WithAll<EndSimulationEntityCommandBufferSystem.Singleton>()
                .WithOptions(EntityQueryOptions.IncludeSystems)
                .Build(ref state);
            
            _eventQuery = new EntityQueryBuilder(Allocator.Temp)
                .WithAll<{component}>()
                .Build(ref state);
            _requestQuery = new EntityQueryBuilder(Allocator.Temp)
                .WithAll<{request}>()
                .Build(ref state);
            using var queries = new NativeList<EntityQuery>(Allocator.Temp);
            queries.Add(_eventQuery);
            queries.Add(_requestQuery);
            
            state.RequireForUpdate(_ecbSingletonQuery);
            state.RequireAnyForUpdate(queries.AsArray());

            _entityType = state.GetEntityTypeHandle();
            _requestType = state.GetComponentTypeHandle<{request}>();
        }}

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {{
            _entityType.Update(ref state);
            _requestType.Update(ref state);
            
            var ecb = _ecbSingletonQuery
                .GetSingleton<EndSimulationEntityCommandBufferSystem.Singleton>()
                .CreateCommandBuffer(state.WorldUnmanaged)
                .AsParallelWriter();
            
            var destroyJob = new DestroyJob
            {{
                Ecb = ecb,
                EntityType = _entityType,
            }};
            
            var requestJob = new RequestJob
            {{
                Ecb = ecb,
                RequestType = _requestType,
                EntityType = _entityType,
            }};

            state.Dependency = destroyJob.ScheduleParallel(_eventQuery, state.Dependency);
            state.Dependency = requestJob.ScheduleParallel(_requestQuery, state.Dependency);
        }}

        [BurstCompile]
        private struct DestroyJob : IJobChunk
        {{
            public EntityCommandBuffer.ParallelWriter Ecb;
            public EntityTypeHandle EntityType;

            [BurstCompile]
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {{
                var entities = chunk.GetNativeArray(EntityType);
                for (int i = 0; i < chunk.Count; i++)
                {{
                    Ecb.DestroyEntity(unfilteredChunkIndex, entities[i]);
                }}
            }}
        }}

        [BurstCompile]
        private struct RequestJob : IJobChunk
        {{
            public EntityCommandBuffer.ParallelWriter Ecb;
            public ComponentTypeHandle<{request}> RequestType;
            public EntityTypeHandle EntityType;

            [BurstCompile]
            public void Execute(in ArchetypeChunk chunk, int unfilteredChunkIndex, bool useEnabledMask, in v128 chunkEnabledMask)
            {{
                var requests = chunk.GetNativeArray(ref RequestType);
                var entities = chunk.GetNativeArray(EntityType);
                for (int i = 0; i < chunk.Count; i++)
                {{
                    var newEntity = Ecb.CreateEntity(unfilteredChunkIndex);
                    Ecb.AddComponent(unfilteredChunkIndex, newEntity, requests[i].Value);
                    Ecb.DestroyEntity(unfilteredChunkIndex, entities[i]);
                }}
            }}
        }}
    }}
{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"
}}")}
";
        }
    }
}